### PR TITLE
Typo in comments ConnectInputs should be CheckInputs

### PR DESCRIPTION
**Pull request by thesoftwarejedi**

### CODE REVIEW

**Comment by thesoftwarejedi** [comment]
I've been peer reviewing and this comment threw me for a curve since "ConnectInputs" could make sense too, yet I believe it to be incorrect.

**Comment by zander** [comment]
nACK

**Comment by christophebiocca** [comment]
Looks right to me as well.

**Comment by mikehearn** [comment]
Thanks. This one could be submitted to Core, I'm sure they'd accept it.

**Comment by zander** [comment]
> This one could be submitted to Core

I would expect that core cherry-picks from XT periodically. Would be nice if people can choose one git repo to develop on...

**Comment by thesoftwarejedi** [comment]
@mikehearn I didn't see it in the core code. I didn't realize it was a cherry pick. I'll look for it there and submit also. 

@zander exactly.

**Comment by thesoftwarejedi** [comment]
@mikehearn actually this is on @gabinandresen commit eaa1d91 re: accurate sigop counts. Unrelated to core.

**Comment by mikehearn** [comment]
Ah, sorry, my mistake. Yes, you're right. I'll merge this.

**Comment by mikehearn** [comment]
Merged

**Pull request closed without merging**
