### PR TITLE
Bitcoin Cash hard fork for DAA and mandatory script flags

### PR DESCRIPTION
**Pull request by dgenr8**
Implement the November 13th, 2017 Bitcoin Cash hard fork as specified at https://github.com/Bitcoin-UAHF/spec/blob/master/nov-13-hardfork-spec.md

The new difficulty adjustment algorithm (DAA) uses a sliding 144-block window and replaces the emergency difficulty adjustment (EDA).

### CODE REVIEW

**Comment by dagurval** [comment]
Changes look good. I've spun up a test node to connect to one of the[ test networks](https://docs.google.com/spreadsheets/d/1l8bYaVQrRHj7YI6b-0kCB9Kehzl552dbtRIyoqZlgqY/).

**Comment by dagurval** [comment]
Successfully synced fork-testnet1

**Comment by dgenr8** [comment]
Successfully synced to cash mainnet, now at height 501314.

**Comment by dagurval** [comment]
ACK

**Pull request merged**
