### PR TITLE
32MB max block size bump

### PR DESCRIPTION
**Pull request by dagurval**

### CODE REVIEW

**Comment by dagurval** [comment]
Moved compact block changes into #345, removed wip tag, rebased

**Comment by dagurval** [comment]
Comments by @dgenr8 addressed in 2c874e6657d1066950a69e59a7a15ec1bf05ac2a

**Comment by dgenr8** [comment]
Squashed @dagurval fixes into their respective commits and added a commit that sets `-thirdhftime=0` `by default until reverted.

**Comment by dagurval** [comment]
The changes you added look good @dgenr8

**Comment by dgenr8** [comment]
Merging 32MB support.
@deadalnix @gandrewstone

**Comment by deadalnix** [comment]
👍

**Pull request merged**
