### PR TITLE
Update default datacarriersize to 220 bytes

### PR DESCRIPTION
**Pull request by dagurval**
https://github.com/Bitcoin-ABC/bitcoin-abc/pull/41

Build on top of #359

### CODE REVIEW

**Comment by dexX7** [comment]
Hi there,

a variation of the original patch was merged. The related commits are:

https://github.com/Bitcoin-ABC/bitcoin-abc/commit/40979c5717cca614eb0f52a8e321a62ba3436b8a
https://github.com/Bitcoin-ABC/bitcoin-abc/commit/cbaa7fe447d2b838ff7b14e243093cbb4f602247 (style only)
https://github.com/Bitcoin-ABC/bitcoin-abc/commit/cbf4410912f6512e481f15270329683d4d4378d4
https://github.com/Bitcoin-ABC/bitcoin-abc/commit/0d1b49c9f37f8549540521e6e02a27c261c6da5a

However, you don't necessarily need an activation for this, given it's just a policy/default value update anyway.

**Comment by dagurval** [comment]
Did you review this cherry-pick @dexX7 ?

> However, you don't necessarily need an activation for this, given it's just a policy/default value update anyway.

Right, I figured that if someone wants to fill XT's mempool with high fee OP_RETURN transactions, some miner is willing to bump their  `-datacarriersize` and eat those fees before the fork.

**Comment by dexX7** [comment]
Hey @dagurval, on the first glimpse it looks good!

**Comment by dgenr8** [comment]
Rebased. ACK.

**Pull request merged**
