### PR TITLE
Testnet for BIP100

### PR DESCRIPTION
**Pull request by dagurval**
Builds on top of #189 and #188

### CODE REVIEW

**Comment by dgenr8** [comment]
Would benefit from rebase now.

**Comment by dagurval** [comment]
Rebased

**Comment by dgenr8** [comment]
ACK. Goes in after #188.

**Comment by dgenr8** [comment]
Pushed Introduce BIP100 testnet as 63754445d0f4d1a93b17ac2bfc591e8f4cef695c to avoid rebasing.

**Pull request closed without merging**
