### PR TITLE
test: move accounting_tests and rpc_wallet_tests to wallet/test

### PR DESCRIPTION
**Pull request by dagurval**
https://github.com/bitcoin/bitcoin/pull/7905

Prerequisite for cashaddr tests

### CODE REVIEW

**Comment by dgenr8** [comment]
Needs rebase

**Comment by dagurval** [comment]
Rebased

**Comment by dgenr8** [comment]
Still has conflict.  Does this belong before or after #316?

**Comment by dagurval** [comment]
Rebased both this one and 316

>  Does this belong before or after #316?
I don't think it matters

**Pull request merged**
