### PR TITLE
Direct headers announcement

### PR DESCRIPTION
**Pull request by dagurval**
Further work on #137. Incorporates #148 because I wanted to use C++11.

This work is based on @sdaftuar work in Bitcoin Core PR #6494 (9fa8c48).
This work is based on @dgenr8 cherry picks in Bitcoin XT #137
    
This implements BIP130. This implementation is a refactor/rewrite on previous work done in Bitcoin Core.
    
This work supports headersfirst together with thin blocks. It is refactored to support unittests, and unittests have been written for most of the logic.

### CODE REVIEW

**Comment by dagurval** [comment]
Rebased

**Comment by dagurval** [comment]
Rebased. Tests still pass.

**Comment by rebroad** [comment]
Isn't there a reason this is not already in XT (and various other forks of Core)?

**Comment by dagurval** [comment]
@rebroad XT forked from Core before this was added

**Comment by dgenr8** [comment]
@dagurval Regarding 47f55bb, did you also want to pull in d41e44c from core#7133?

**Comment by dgenr8** [comment]
ACK other than preceding comment.  Tested on mainnet for 1 week.

**Comment by dagurval** [comment]
@dgenr8 I replaced 4aacaf6 with d41e44c9 and all tests pass.

**Pull request merged**
