### PR TITLE
Tx metadata in all undo records & new coins interface

### PR DESCRIPTION
**Pull request by dagurval**
422634e2f and cb2c7fdac from Core#10195

No conflicts.

### CODE REVIEW

**Comment by dgenr8** [comment]
This change commits (or maybe further commits) us to a chainstate rebuild on next launch.  Just making sure we see a path to the complete upgrade from here.

**Comment by dagurval** [comment]
This is backward compatible, but not forward compatible. It won't be possible to downgrade without reindexing.

Backward compatibility is also maintained, see `ApplyTxInUndo` in #411. Although, I don't mind  simplifying the code by removing backward compatibility, thus forcing reindex. Computer time is less valuable than developer time.

**Comment by dgenr8** [comment]
My only concern is that we have the complete upgrade in sight when we start sacrificing compatibility.

**Comment by dgenr8** [comment]
utACK

**Pull request merged**
