### PR TITLE
Fix init scripts

### PR DESCRIPTION
**Pull request by keo**
fixed init scripts so they work with the new binary name.

### CODE REVIEW

**Comment by dgenr8** [comment]
ping @stevemyers

**Comment by stevemyers** [comment]
Good idea @keo, I also suggest if we're going to rename these files we should change the daemon name inside these files also to ```bitcoinxt```.  

And this also brings up another topic I'd like to get feed back from @mikehearn and @gavinandresen, are you happy with the daemon being called ```bitcoinxt```, or should we change it to ```bitcoinxtd``` ?  Ending the filename with a ```d``` is more in line with the typical unix daemon naming convention.   I realize this is a minor quibble but changing file name shouldn't be that hard and improves clarity for its function.

**Comment by mikehearn** [comment]
Don't care either way, xtd is also fine by me. You're the package maintainer - use the power ;)

**Comment by mikehearn** [comment]
Thanks keo!

**Comment by keo** [comment]
thanks for merging - my VM building scripts now work directly from the git repo. :)

**Comment by stevemyers** [comment]
I've updated bitcoinxt to bitcoinxtd in #55, anyone who's interested please review.  Thanks!

**Pull request merged**
