### PR TITLE
UAHF: Move check for fork activation to a function 

### PR DESCRIPTION
**Pull request by dagurval**
Regtests fork at genesis, so the check in ConnectTip needs to support this.

### CODE REVIEW

**Comment by dgenr8** [comment]
Could we also use the new function [here](https://github.com/dagurval/bitcoinxt/blob/a3b7eca93a2941b293e46cd9180ad88ce83b4849/src/main.cpp#L3447)?

**Comment by dagurval** [comment]
Added unittests for the new function.

**Comment by dgenr8** [comment]
Looks good. All tests pass. I'm syncing to a fork point on testnet now.

**Comment by dgenr8** [comment]
ACK

**Pull request merged**
