### PR TITLE
C++11

### PR DESCRIPTION
**Pull request by dagurval**
Cherry-picks from https://github.com/bitcoinclassic/bitcoinclassic/pull/162

### CODE REVIEW

**Comment by dagurval** [comment]
Rebased

**Comment by dgenr8** [comment]
I built and ran tests successfully.  To get this into a release, the gitian environment needs to be updated, as was done in https://github.com/bitcoin/bitcoin/pull/6900.

Aside from being deterministic, gitian is how Windows builds get done.

**Comment by dagurval** [comment]
I cherry picked that PR into https://github.com/dagurval/bitcoinxt/tree/gitian, is this enough?

**Comment by dgenr8** [comment]
We need commits to this PR, then using the docs ``doc/gitian-building.md``, ``contrib/gitian-descriptors/README.md`` and ``doc/release-process.md`` as updated here, you should be able to build from your C++11 source.  Then others can do the same and we can even compare hashes ;)

**Comment by dagurval** [comment]
I added the commits to this PR. Can I get away with not doing a gitian build? 😅

**Comment by dgenr8** [comment]
You could if I was excited about C++11 :smiling_imp:

**Comment by dagurval** [comment]
Closes in favor of #163

**Pull request closed without merging**
