### PR TITLE
Release-time changes for K

### PR DESCRIPTION
**Pull request by dgenr8**

### CODE REVIEW

**Comment by dgenr8** [comment]
``p2p-compactblocks.py`` has started failing consistently for me locally. Let's see what jenkins says.

**Comment by dgenr8** [comment]
p2p-compactblocks.py has started failing consistently for me locally. Jenkins also shows a failure.

**Comment by dagurval** [comment]
After debugging, I've found the issue with p2p-compactblocks to be that a utxo was being spent twice. This is the fix:

```
@@ -801,7 +803,7 @@ class CompactBlocksTest(BitcoinTestFramework):
-        utxo = self.utxos[0]
+        utxo = self.utxos.pop(0)
```

Let's fix this in a seperate PR.

**Review by dagurval — APPROVED** [review]

**Comment by dgenr8** [comment]
https://github.com/bitcoinxt/bitcoinxt/pull/511#issuecomment-436890901 does not fix the test for me
```
Advancing to segwit activation

Running tests, post-segwit activation...
	Testing compactblock construction...
Assertion failed: Block sync failed
  File "/home/dgenr8/bitcoinxt/qa/rpc-tests/test_framework/test_framework.py", line 154, in main
    self.run_test()
  File "./p2p-compactblocks.py", line 942, in run_test
    sync_blocks(self.nodes)
  File "/home/dgenr8/bitcoinxt/qa/rpc-tests/test_framework/util.py", line 135, in sync_blocks
    raise AssertionError("Block sync failed")
```

**Pull request merged**
