### PR TITLE
Extract curlwrapper from ipgroup for re-use

### PR DESCRIPTION
**Pull request by dagurval**
This PR has fixes for issues pointed out by Mike in review. I squashed the fixes into the previous commit, to see just the changes see this commit: https://github.com/dagurval/bitcoinxt/commit/9b5de8d94b139fdbe91dd4d17ec38913bfe30ea3

Changes:
- Handle errors from curl_easy_perform
- Throw errors when status code is not 200 OK
- Expose DummyCurlWrapper to simplify the main interface

### CODE REVIEW

**Comment by mikehearn** [comment]
Untested but this looks good to me.

Would like another review.

**Comment by mikehearn** [comment]
@dagurval whose court is the ball in here? Is this waiting for me to take another look or are there still pending changes you'd like to make?

**Comment by dagurval** [comment]
I pushed a commit that I think fixes issues and adds suggestions pointed out by @zander. Correct me if I'm wrong. A exception is not adding a setOpt method. I can't think of a good way to wrap setOpt since curl_easy_setopt is a variadic function. 

If this looks OK, I'll squash it with the previous commit.

**Comment by dgenr8** [comment]
@dagurval Please rebase or close.

**Comment by dagurval** [comment]
It's already in master :+1:

**Pull request closed without merging**
