### PR TITLE
Continuing port of java comparison tool

### PR DESCRIPTION
**Pull request by dagurval**
Builds on top of #259 

Port of https://github.com/bitcoin/bitcoin/pull/8141 - Continuing port of java comparison tool

### CODE REVIEW

**Comment by dgenr8** [comment]
Needs rebase

**Comment by dagurval** [comment]
rebased

**Comment by dgenr8** [comment]
I proposed some additions here: https://github.com/dagurval/bitcoinxt/pull/1

**Comment by dgenr8** [comment]
All tests pass including --runbarelyexpensive. Squash away.

**Comment by dagurval** [comment]
Squashed. Thanks for the additions.

**Comment by dgenr8** [comment]
ACK

**Pull request merged**
