### PR TITLE
Use python2/3 syntax

### PR DESCRIPTION
**Pull request by dagurval**
Cherry-picks of https://github.com/bitcoin/bitcoin/pull/7778. That PR touches a lot of files and code, including some tests we don't have and some that are not interesting (like RBF etc.). We also already had some of these changes. I've attempted to pull over everything relevant.

### CODE REVIEW

**Comment by dagurval** [comment]
The test pruning.py failed. Don't know if it's related.

```
Running 2nd level testscript pruning.py ...
Initializing test directory /tmp/testY17RgG
Warning! This test requires 4GB of disk space and takes over 30 mins (up to 2 hours)
Mining a big blockchain of 995 blocks
Check that we haven't started pruning yet because we're below PruneAfterHeight
Success
Though we're already using more than 550MiB, current usage: 593.0
Mining 25 more blocks should cause the first block file to be pruned
Assertion failed: blk00000.dat not pruned when it should be
  File "/home/dagurval/bitcoinxt/qa/rpc-tests/test_framework/test_framework.py", line 144, in main
    self.run_test()
  File "/home/dagurval/bitcoinxt/qa/rpc-tests/pruning.py", line 275, in run_test
    self.test_height_min()
  File "/home/dagurval/bitcoinxt/qa/rpc-tests/pruning.py", line 94, in test_height_min
    raise AssertionError("blk00000.dat not pruned when it should be")

```

**Comment by dgenr8** [comment]
pruning.py was working within the last few commits.

**Comment by dagurval** [comment]
I picked https://github.com/bitcoin/bitcoin/pull/6224 - "Be even stricter in processing unrequested blocks" into this PR. I've ran `pruning.py` multiple times without issues.

rpcbind_test.py hangs for me. All other tests pass.

**Comment by dgenr8** [comment]
ACK inspection.
All tests pass.

**Pull request merged**
