### PR TITLE
Test framework improvements

### PR DESCRIPTION
**Pull request by dagurval**
Builds on top of #258 

Great improvements for the qa test framework. Includes:

https://github.com/bitcoin/bitcoin/pull/7851/ - [qa] pull-tester: Don't mute zmq ImportError
https://github.com/bitcoin/bitcoin/pull/7971/ - [qa] Refactor test_framework and pull tester
https://github.com/bitcoin/bitcoin/pull/8056/ - [qa] Remove hardcoded "4 nodes" from test_framework
https://github.com/bitcoin/bitcoin/pull/7972 - [qa] pull-tester: Run rpc test in parallel
https://github.com/bitcoin/bitcoin/pull/8713 - [qa] create_cache: Delete temp dir when done

### CODE REVIEW

**Comment by dagurval** [comment]
"tests: Check Content-Type header returned from RPC server" https://github.com/bitcoin/bitcoin/pull/7833 pulled over. rpcbind_test now passes.

**Comment by dgenr8** [comment]
Needs rebase.

**Comment by dagurval** [comment]
rebased

**Comment by dgenr8** [comment]
ACK. This is great!

**Pull request merged**
