### PR TITLE
Bloom filter updates

### PR DESCRIPTION
**Pull request by dagurval**
* Improve rolling bloom filter performance - https://github.com/bitcoin/bitcoin/pull/7934/             
* trivial: fix bloom filter init to isEmpty = true - https://github.com/bitcoin/bitcoin/pull/9060      
* Bloomfilter: parameter variables made constant - https://github.com/bitcoin/bitcoin/pull/9750        
* Fix msvc compiler error C4146 (minus operator applied to unsigned type) - https://github.com/bitcoin/bitcoin/pull/9916

### CODE REVIEW

**Comment by dagurval** [comment]
If #298 is merged first, then I can also cherry pick a benchmark commit to this PR

**Comment by dgenr8** [comment]
Ok reviewing #298 first.

**Comment by dagurval** [comment]
Rebased and added benchmark

**Comment by dgenr8** [comment]
```
dgenr8@dgenr8-VirtualBox:~/bitcoinxt$ src/bench/bench_bitcoin 
Benchmark,count,min,max,average
RollingBloom-refresh,1,0.001404,0.001404,0.001404
RollingBloom-refresh,1,0.001755,0.001755,0.001755
RollingBloom-refresh,1,0.001535,0.001535,0.001535
RollingBloom,196607,3.98234e-06,2.44314e-05,5.37991e-06
Sleep100ms,10,0.100104,0.100956,0.100351
Trig,10485759,7.61647e-08,1.50204e-05,1.01944e-07
```

**Pull request merged**
