### PR TITLE
Remove option -logips. Re-add logging of IPs.

### PR DESCRIPTION
**Pull request by dagurval**
We should either remove or or maintain this feature. I prefer for less code (remove).

`-logips` was adedded in https://github.com/bitcoin/bitcoin/pull/3764

### CODE REVIEW

**Comment by dagurval** [comment]
If we want to maintain instead:
* ID needs to be added to "peer misbehaved" output. Currently shows only IP. Can't know what peer was misbehaved without adding logips=1
* IPGroup name needs to be obfuscated, default name for IPGroup is the IP address. IPGroup is logged when a peer connects.

**Comment by dgenr8** [comment]
Rebased.

**Comment by dgenr8** [comment]
I think we should maintain this option.  It's nice to be able to share log snippets without worrying about revealing your peer IP's.

**Comment by dagurval** [comment]
Closing for now

**Pull request closed without merging**
