### PR TITLE
Easy to use gitian building script

### PR DESCRIPTION
**Pull request by dagurval**
https://github.com/bitcoin/bitcoin/pull/8566 - Easy to use gitian building script
https://github.com/bitcoin/bitcoin/pull/11391 - Remove lxcbr0 lines from gitian-build.sh
f6b3382 (squashed into next commit), b9e79ab and 564a172 from https://github.com/bitcoin/bitcoin/pull/10773/
https://github.com/bitcoin/bitcoin/pull/12394 - gitian-builder.sh: fix --setup doc, since lxc is default
https://github.com/bitcoin/bitcoin/pull/12527 - gitian-build.sh: fix signProg being recognized as two parameters
https://github.com/bitcoin/bitcoin/pull/13320 - Ensure gitian-build.sh uses bash

Tested by building Windows and Linux versions for 0.11I and the sha256sums match.

Documentation for using this is located here: https://github.com/bitcoin-core/docs/blob/master/gitian-building.md

### CODE REVIEW

**Comment by dgenr8** [comment]
@xt-bot retest this

**Comment by dagurval** [comment]
Did you use your existing Gitian VM? If so, is it the same version of debian as [in the documentation?](https://github.com/bitcoin-core/docs/blob/master/gitian-building/gitian-building-create-vm-debian.md)

**Comment by dgenr8** [comment]
@dagurval Thanks, turns out I was expecting it to do much more than it does.  I built all three platforms fine.  Should we turn on OSX by default?

ACK

**Comment by dagurval** [comment]
> Should we turn on OSX by default?

I disabled it because we haven't released OSX binaries for some time. I'm all for enabling it if we have the resources to maintain minimal support for OSX (maybe @jeffgran is interested?).

**Pull request merged**
