### PR TITLE
C++11 with gitian support

### PR DESCRIPTION
**Pull request by dgenr8**
Yet another go at C++11 support.   Based on #163, it also includes the build system updates needed to support gitian without splitting the repo.

As a bonus, we also get working ARM and Arch gitian builds.

### CODE REVIEW

**Comment by dgenr8** [comment]
To aid in testing gitian, I pushed tag ``vcpp11``.  To test gitian:
```
cd bitcoinxt
git fetch --tags
git checkout vcpp11
cd ../gitian-builder
./bin/gbuild --commit bitcoin=vcpp11 ../bitcoinxt/contrib/gitian-descriptors/gitian-linux.yml
```

**Comment by dagurval** [comment]
```
2cc20e4fc0b4736d37cb18f53bb799937892a2b42e4121fceea6e18252afff64  bitcoin-xt-0.11.0-G-aarch64-linux-gnu.tar.gz
af7a3a9ae9c4097d4f29946aa9e37a8de626355041502966a76271f8e602e2a1  bitcoin-xt-0.11.0-G-arm-linux-gnueabihf.tar.gz
260a575b488cad1613ef05ecc4b943439ff4a36d557d1454991aa52dcde3cd3b  bitcoin-xt-0.11.0-G-linux32.tar.gz
14d305b0f91b8d6ffeabcd20d16ce410952579a5d49e4676cc71a56632e621a7  bitcoin-xt-0.11.0-G-linux64.tar.gz
c33494b3319616643b545d16b9a0ffef7df140e98f0dec2872c91e2dea8b4efe  src/bitcoin-xt-0.11.0-G.tar.gz
99afdefae938cd112d561f133d387e69c5ca0a48392caf2240e0fa57cd5407ad  bitcoin-linux-0.11-res.yml

```

**Comment by dgenr8** [comment]
Bingo, all match. Next time just share the first halves of the hashes so I can prove it to you :)

**Comment by dgenr8** [comment]
My hash stems for windows
```
d0c902d9  bitcoin-0.11.0-win32-setup-unsigned.exe
98db7fa8  bitcoin-0.11.0-win64-setup-unsigned.exe
74862c17  bitcoin-xt-0.11.0-G-win-unsigned.tar.gz
87d4cb51  bitcoin-xt-0.11.0-G-win32.zip
cf258c44  bitcoin-xt-0.11.0-G-win64.zip
c33494b3  src/bitcoin-xt-0.11.0-G.tar.gz
a1c53f8f  bitcoin-win-0.11-res.yml
```

**Comment by dagurval** [comment]
All files except the .yml match with my build:
```
d0c902d9a16662f596db6d8749b249c01bba568213e9fb65fbdd101fe8bd491a  bitcoin-0.11.0-win32-setup-unsigned.exe
98db7fa813014d619fce8a3931e0f86db9898adc1e8e3adaaab749a0860e4af8  bitcoin-0.11.0-win64-setup-unsigned.exe
74862c1761631f14af3f18c006b7faefd68b8d7f56ff87df23c3f549fc42be9a  bitcoin-xt-0.11.0-G-win-unsigned.tar.gz
87d4cb510917220e80d3d742f6d9044e48a2848704415888303760e4bed12a10  bitcoin-xt-0.11.0-G-win32.zip
cf258c446f7f6fd4d6d0ab89aa331bfd6a1c976c757637ca867c716dcbf39a98  bitcoin-xt-0.11.0-G-win64.zip
c33494b3319616643b545d16b9a0ffef7df140e98f0dec2872c91e2dea8b4efe  src/bitcoin-xt-0.11.0-G.tar.gz
36660dce8ede10459af7e9812f1111adcab423ee16570576e2e3a741e2fd5189  bitcoin-win-0.11-res.yml

```

**Comment by rebroad** [comment]
Corresponds with https://github.com/bitcoin/bitcoin/pull/7711 I think.. I just tried gitian building bitcoin core the other day and struggled - I think the documentation is a bit off. Will try with BitcoinXT next to see if you're more on it - I especially want to get ARM binaries produced..

**Comment by dgenr8** [comment]
@rebroad That commit is one of the cherry-picks in this PR.

**Pull request merged**
