### PR TITLE
implement uacomment config parameter

### PR DESCRIPTION
**Pull request by SoreGums**
which can add comments to user agent as per BIP-0014

limit total length of user agent comments
Reworked-By: Wladimir J. van der Laan <laanwj@gmail.com>

Cherry Picked from 7b79cbd722d35b8113d5136b06d4a8e5fd569fc6
merged into StealthMode by SoreGums <nicholas.orr@zxgen.net>

### CODE REVIEW

**Comment by jonasschnelli** [comment]
https://github.com/bitcoin/bitcoin/pull/6462

**Comment by mikehearn** [comment]
Is there some specific reason to pull this patch in earlier than the next rebase/merge with Core? It'll get in eventually as XT plans to pull useful code in from Core when they do new releases.

**Comment by SoreGums** [comment]
No reason, other than it was not a clean pull due to the stealth mode that was added to xt. I wanted it now, so made it work is all.

**Comment by mikehearn** [comment]
OK, fair enough. It's a small patch, we could throw this in for 0.11C and then remove/redo it when the next rebase happens.

**Comment by dgenr8** [comment]
@SoreGums Please rebase or close.

**Comment by dgenr8** [comment]
Closed in favor of #108.

**Pull request closed without merging**
