### PR TITLE
gitian: renamed bitcoinxt daemon to bitcoinxtd, also updated related scripts and readme files

### PR DESCRIPTION
**Pull request by stevemyers**
This request changes the bitcoinxt daemon name to ```bitcoinxtd``` for the gitian-debian installer.  Ending the filename with a ```d``` is more in line with ```bitcoind``` in core and is the typical unix daemon naming convention.  I also renamed ```bitcoinxt``` to ```bitcoinxtd``` in the contrib/init scripts.  

Please review if you have time @keo as I updated the files you recently changed.  Thanks!

@mikehearn  I hope this looks OK, thanks for letting me address my own quibble. :-)

### CODE REVIEW

**Comment by mikehearn** [comment]
OK, that's a big patch, but I'll assume you tested it as I don't have all the different setups here needed to check all the different init scripts.

**Comment by stevemyers** [comment]
Ah ya.. why don't you hold off on the merge.  I only tested the gitian-debian build.  They are all just simple    changes but I will spin up some VMs to test the contrib/init files too.

**Comment by mikehearn** [comment]
OK. I'll give keo some time to comment too. I'll probably start on the 0.11B release tomorrow or Friday though.

**Comment by NanoAkron** [comment]
Is it Bitcoin XT or BitcoinXT?

**Comment by stevemyers** [comment]
I've tested the systemd ```bitcoinxtd.system``` (systemd) file; it's identical to the one in gitian-debian.  I've also just tested the ```bitcoinxtd.init``` (init.d) script with CentOS6 (CentOS7 uses sytemd).  I don't have a ChromeOS system available to test the ```bitcoinxtd.conf``` (Upstart) init script.  I also haven't tested the ```bitcoinxtd.openrc``` (OpenRC) scripts on a gentoo system (it's a real PITA to install a fresh gentoo vm).   If you'd prefer  to wait until we have testing on all systems then best to leave this pull req out of the 0.11B release.

**Comment by stevemyers** [comment]
@NanoAkron I think "Bitcoin XT" is correct per the [Bitcoin XT website](https://bitcoinxt.software/).

**Comment by mikehearn** [comment]
Merged, thanks!

**Comment by stevemyers** [comment]
Thanks Mike!

**Pull request closed without merging**
