### PR TITLE
Make the XT alphabetical patchlevel appear in version strings.

### PR DESCRIPTION
**Pull request by mikehearn**

### CODE REVIEW

**Comment by gavinandresen** [comment]
make check fails:
```
FAIL: test/test_bitcoin
=======================

Running 165 test cases...
test/util_tests.cpp:354: error in "test_FormatSubVersion": check FormatSubVersion("Test", 99900, std::vector<std::string>()) == std::string("/Test:0.9.99/") failed [/Test:0.9.99B/ != /Test:0.9.99/]
test/util_tests.cpp:355: error in "test_FormatSubVersion": check FormatSubVersion("Test", 99900, comments) == std::string("/Test:0.9.99(comment1)/") failed [/Test:0.9.99B(comment1)/ != /Test:0.9.99(comment1)/]
test/util_tests.cpp:356: error in "test_FormatSubVersion": check FormatSubVersion("Test", 99900, comments2) == std::string("/Test:0.9.99(comment1; comment2)/") failed [/Test:0.9.99B(comment1; comment2)/ != /Test:0.9.99(comment1; comment2)/]

*** 3 failures detected in test suite "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)
```

**Comment by mikehearn** [comment]
Fixed, please take another look. Thanks!

**Comment by gavinandresen** [comment]
ACK

**Comment by mikehearn** [comment]
Merged

**Pull request closed without merging**
