### PR TITLE
libevent-based http server

### PR DESCRIPTION
**Pull request by dagurval**
Cherry picks of https://github.com/bitcoin/bitcoin/pull/5677

Includes commits in PR #171 

This PR also cherry picks 6239, 6262 and 6456 from Core.

### CODE REVIEW

**Comment by dagurval** [comment]
added fixes in https://github.com/bitcoin/bitcoin/pull/6695

**Comment by dgenr8** [comment]
Needs rebase.

**Comment by dagurval** [comment]
I re-did this port. Found a nice list of cherries in the zcash project https://github.com/zcash/zcash/pull/2176

**Unrelated:**
This PR was pulled in to reduce conflicts:
* [REST] Add memory pool API - https://github.com/bitcoin/bitcoin/pull/6013

**Libevent related:**
* libevent-based http server - https://github.com/bitcoin/bitcoin/pull/5677
* libevent http fixes - https://github.com/bitcoin/bitcoin/pull/6695
* Avoid a compile error on hosts with libevent too old for EVENT_LOG_WARN - https://github.com/bitcoin/bitcoin/pull/7016
* bitcoin-cli: More detailed error reporting - https://github.com/bitcoin/bitcoin/pull/8722
* depends: Add libevent compatibility patch for windows - https://github.com/bitcoin/bitcoin/pull/8730
* Trivial: Add common failure cases for rpc server connection failure - https://github.com/bitcoin/bitcoin/pull/9073
* bitcoin-cli: Make error message less confusing - https://github.com/bitcoin/bitcoin/pull/9265
* [Refactor] RAII of libevent stuff using unique ptrs with deleters - https://github.com/bitcoin/bitcoin/pull/9387
* [depends] libevent 2.1.7rc - https://github.com/bitcoin/bitcoin/pull/9471
* Skip RAII event tests if libevent is built without event_set_mem_functions - https://github.com/bitcoin/bitcoin/pull/9647
* Docs: add details to -rpcclienttimeout doc - https://github.com/bitcoin/bitcoin/pull/9903
[TRIVIAL] Fix typo: 

A couple of PRs in the zcash were py3 fixes. We don't have py3 yet.

**Comment by dgenr8** [comment]
ACK

**Pull request merged**
