### PR TITLE
Cherry-pick updates to contrib/linearize

### PR DESCRIPTION
**Pull request by dgenr8**
https://github.com/bitcoin/bitcoin/pull/6372 Update Linearize tool to support Windows paths
https://github.com/bitcoin/bitcoin/pull/9373 Support hash byte reversal, support python3
https://github.com/bitcoin/bitcoin/pull/9580 Fix various minor linearization script issues
https://github.com/bitcoin/bitcoin/pull/10104 Adds the a datadir option to the linearize configuration file

Only one trivial conflict.  Bypassed changes from broad refactorings.

### CODE REVIEW

**Comment by dgenr8** [comment]
@dagurval I don't see cookies mentioned in the linearize README but code to read the .cookie file got included.  Are you saying you don't mind that, or suggesting this be made dependent on bringing over https://github.com/bitcoin/bitcoin/pull/6388?

**Comment by dagurval** [comment]
This got added to the README, while in practice rpcuser and rpcpassword are always required by XT:

> RPC: `datadir` (Required if `rpcuser` and `rpcpassword` are not specified)

I don't mind that the .cookie read code got included for the sake of simpler cherry-picking in the future. I'm not suggesting you bring over 6338.

**Comment by dgenr8** [comment]
Setting -rpcuser and/or -rpcpassword on the server command line does work though.

**Comment by dagurval** [comment]
OK 👍

**Pull request merged**
